'packages:biome-config':
- changed-files:
  - any-glob-to-any-file: packages/biome-config/**

'packages:eslint-config':
- changed-files:
  - any-glob-to-any-file: packages/eslint-config/**

'packages:prettier-config':
- changed-files:
  - any-glob-to-any-file: packages/prettier-config/**

'packages:ts-config':
- changed-files:
  - any-glob-to-any-file: packages/ts-config/**

'packages:utilities':
- changed-files:
  - any-glob-to-any-file: packages/utilities/**
